version: "3.10"

services:
  nginx:
    build:
      context: ./nginx
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"